// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MediClientMac
{
	public partial class AlertBoxClickViewController : NSViewController
	{
		public AlertBoxClickViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
