// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MediClientMac
{
	public partial class AlertOnGreenClickViewController : NSViewController
	{
		public AlertOnGreenClickViewController (IntPtr handle) : base (handle)
		{
			Clients clt = new PreferencesViewController().GetLatestClient();
			label1.StringValue += clt.ClientName;

			label2.StringValue = clt.AlertMessage;
			label3.StringValue = DateTime.Now.ToShortTimeString().ToString() + " - " + DateTime.Now.ToShortDateString();

		}
		private NSViewController _presentor;
		public NSViewController Presentor
		{
			get { return _presentor; }
			set { _presentor = value; }
		}
		partial void button1(NSObject sender)
		{
			Presentor.DismissViewController(this);
		}
		public override void ViewDidLayout()
		{
			base.ViewDidLayout();

		}

	}
}
