// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MediClientMac
{
	public partial class AlertOnRedClickViewController : NSViewController
	{
		public AlertOnRedClickViewController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			Clients clt = new PreferencesViewController().GetLatestClient();
			label1.StringValue += clt.ClientName;

			label2.StringValue = clt.AlertMessage;
			label3.StringValue = DateTime.Now.ToShortTimeString().ToString() + " - " + DateTime.Now.ToShortDateString();
		

		}
		private void button1_Click(object sender, EventArgs e)
		{
			Presentor.DismissViewController(this);
		}
		private NSViewController _presentor;
		public NSViewController Presentor
		{
			get { return _presentor; }
			set { _presentor = value; }
		}
		private void button2_Click(object sender, EventArgs e)
		{

		}
	}
}
