// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MediClientMac
{
	public partial class PopOverViewController : NSViewController
	{
		public PopOverViewController (IntPtr handle) : base (handle)
		{
		}
		partial void exit_app(NSObject sender)
		{
			NSApplication.SharedApplication.Terminate(this);
		}
	}
}
